name: Main

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ env.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/myapp:latest

  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to dev env
        run: |
          # Add your deployment script here

      - name: Slack notification on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2

        with:
          status: "Deployment to dev env failed"
          text: "There was a failure during deployment to the dev environment."

  staging-approval:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2

        with:
          status: "Staging Deployment Approval"
          text: "A deployment to the staging environment requires approval. Please review and respond."

      - name: Wait for approval
        uses: repo-sync/pull-request@v2

        id: approval

        with:
          destination_repository: "${{ github.repository }}"
          source_branch: "${{ github.ref }}"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify approval
        run: |
          if [[ "${{ steps.approval.outputs.approved }}" == "true" ]]; then
            echo "Approval received. Proceeding with deployment to staging."
          else
            echo "Deployment to staging is NOT approved. Exiting the workflow."
            exit 1
          fi

  deploy-to-staging:
    needs: staging-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to staging env
        run: |
          # Add your staging deployment script here
