name: Main

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: "danielsmith0831"
  DOCKERHUB_TOKEN: "Daniel.Smith.hub.docker.com@0831"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ env.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/myapp:latest

  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to dev env
        run: |
          # Add your deployment script here

      - name: Slack notification on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2

        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

        with:
          status: "Deployment to dev env failed"
          text: "There was a failure during deployment to the dev environment."

  staging-approval:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2

        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

        with:
          status: "Staging Deployment Approval"
          text: "A deployment to the staging environment requires approval. Please review and respond."

      - name: Wait for approval
        uses: repo-sync/pull-request@v2

        id: approval

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permissions: read

      - name: Verify approval
        run: |
          if [[ "${{ steps.approval.outputs.approved }}" == "true" ]]; then
            echo "Approval received. Proceeding with deployment to staging."
          else
            echo "Deployment to staging is NOT approved. Exiting the workflow."
            exit 1
          fi
